version: '3'

services:
  image: postgre
  environment:
    POSTGRES_PASSWORD: "your-password"
  ports:
    - "5432:5432"
  volumes:
    - /home/$USER/docker-compose/postgres/volume:/var/lib/postgresql/data
  networks:
    - postgres-network
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "your-email@email.com"
      PGADMIN_DEFAULT_PASSWORD: "your-password
    ports:
      - 16543:80
    depends_on:
      - postgresql
    networks:
      - postgres-network
    
networks:
  postgres-network:
    driver: brigde
