version: '3'
services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - /home/$USER/docker/compose/mongodb/volume:/var/lib/mongo/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME='root_username'
      - MONGO_INITDB_ROOT_PASSWORD='rootpassword'
    networks:
      - mongodb-network

networks:
  mongodb-network:
    driver: brigde
